### ISSUE TITLE
Fails to compile with newer versions of Boost.

### ISSUE THREAD

**Issue by alexskc** [eglaysher/rlvm#63]
Compiles successfully under Boost 1.56, and fails under Boost 1.57.

Returns many near-identical errors, such as

     /usr/include/boost/smart_ptr/scoped_ptr.hpp:121:31: note:   template argument deduction/substitution failed:
     In file included from vendor/luabind/include/luabind/detail/call_member.hpp:34:0,
                      from vendor/luabind/include/luabind/wrapper_base.hpp:31,
                      from vendor/luabind/include/luabind/back_reference.hpp:27,
                      from vendor/luabind/include/luabind/class.hpp:93,
                      from vendor/luabind/include/luabind/luabind.hpp:28,
                      from test/script_machine/script_world.h:35,
                      from test/script_machine/script_world.cc:27:
     vendor/luabind/include/luabind/object.hpp:553:37: note:   'const luabind::detail::basic_iterator<luabind::detail::raw_access>' is not derived from 'const boost::scoped_ptr<T>'
            return boost::operator op(x, y); \
                                          ^

**Comment by enmarei** [comment]
Still an issue on Fedora 23 with Boost 1.58.
```
[liveuser@localhost rlvm]$ dnf list installed boost
Last metadata expiration check performed 0:38:32 ago on Tue Nov 10 16:29:30 2015.
Installed Packages
boost.x86_64                        1.58.0-8.fc23                        @fedora
[liveuser@localhost rlvm]$ scons --release
scons: Reading SConscript files ...
Checking for Boost version >= 1.40... no
Boost version >= 1.40 needed to compile rlvm!
```
