### ISSUE TITLE
Can't play past the Prologue in Clannad English Edition

### ISSUE THREAD

**Issue by eglaysher** [eglaysher/rlvm#74]
Playing in the official interpreter, this is where the achievement "The hill goes on" pops. In rlvm, we exit to the main menu. 

Of interest is an unhandled "CallStackSize" function call. This appears to happen in SEEN 9820.

**Comment by xy2iii** [comment]
If you are looking for a quick fix to this issue - launch rlvm in your terminal with these arguments:

`rlvm --start-seen 0414 <path to Clannad folder>`

**Comment by NuclearMachine** [comment]
How would I do it with the rlvm-android port @xy2iii? The prologue crashes as well.
