### ISSUE TITLE
Latest rlvm from git does not compile

### ISSUE THREAD

**Issue by cyberl33t** [eglaysher/rlvm#76]
The latest rlvm pulled from git fails to compile:

`Compiling build/release/src/systems/base/graphics_object.o ...`
`Compiling build/release/src/systems/base/graphics_object_data.o ...`
`src/systems/base/graphics_object.cc: In member function 'void GraphicsObject::EndObjectMutatorMatching(RLMachine&, int, const string&, int)':`
`src/systems/base/graphics_object.cc:834:5: error: 'cerr' is not a member of 'std'`
     `std::cerr << "Warning: We only do immediate endings in "`
     `^`
`Compiling build/release/src/systems/base/graphics_object_of_file.o ...`
`scons: *** [build/release/src/systems/base/graphics_object.o] Error 1`
`scons: building terminated because of errors.`

Using gcc-4.9.3, scons-2.5.0, boost-1.61.0 on Gentoo Linux. Earlier versions compiled & worked fine, trying to recompile because of breakage caused by boost update. Do you need the whole build log?

**Comment by eglaysher** [comment]
Can't reproduce with gcc 5.2.1-22ubuntu2, but that looks like it's just
missing a system header. Pushing a theoretical fix; reopen if it doesn't
work?

On Sun, May 22, 2016 at 9:44 AM, cyberl33t <notifications@github.com> wrote:

> The latest rlvm pulled from git fails to compile:
>
> Compiling build/release/src/systems/base/graphics_object.o ...
> Compiling build/release/src/systems/base/graphics_object_data.o ...
> src/systems/base/graphics_object.cc: In member function 'void
> GraphicsObject::EndObjectMutatorMatching(RLMachine&, int, const string&,
> int)':
> src/systems/base/graphics_object.cc:834:5: error: 'cerr' is not a member
> of 'std'
> std::cerr << "Warning: We only do immediate endings in "
> ^
> Compiling build/release/src/systems/base/graphics_object_of_file.o ...
> scons: *** [build/release/src/systems/base/graphics_object.o] Error 1
> scons: building terminated because of errors.
>
> Using gcc-4.9.3, scons-2.5.0, boost-1.61.0 on Gentoo Linux. Earlier
> versions compiled & worked fine, trying to recompile because of breakage
> caused by boost update. Do you need the whole build log?
>
> —
> You are receiving this because you are subscribed to this thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/eglaysher/rlvm/issues/76>
>



-- 
-- Elliot

**Comment by cyberl33t** [comment]
Thanks, your theoretical fix, in practice, worked!
