### ISSUE TITLE
Clannad (Full Voice) Crash on Android

### ISSUE THREAD

**Issue by zagingi** [eglaysher/rlvm#83]
Hello, I am using Clannad (Full Voice) English patch and RLVM keeps crashing whenever I try to run the game. Anyone have the issue that has fixed it? Any info would be great! Thanks everyone!

**Comment by eglaysher** [comment]
We don't ship an Android build, and there's no Android code in the rlvm repository. I know someone else did a port, but they never upstreamed their code.
